
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[QRTZ_FIRED_TRIGGERS]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
BEGIN
	CREATE TABLE [dbo].[QRTZ_FIRED_TRIGGERS] (
	  [SCHED_NAME] [NVARCHAR] (120)  NOT NULL ,
	  [ENTRY_ID] [NVARCHAR] (140)  NOT NULL ,
	  [TRIGGER_NAME] [NVARCHAR] (150)  NOT NULL ,
	  [TRIGGER_GROUP] [NVARCHAR] (150)  NOT NULL ,
	  [INSTANCE_NAME] [NVARCHAR] (200)  NOT NULL ,
	  [FIRED_TIME] [BIGINT] NOT NULL ,
	  [SCHED_TIME] [BIGINT] NOT NULL ,
	  [PRIORITY] [INTEGER] NOT NULL ,
	  [STATE] [NVARCHAR] (16)  NOT NULL,
	  [JOB_NAME] [NVARCHAR] (150)  NULL ,
	  [JOB_GROUP] [NVARCHAR] (150)  NULL ,
	  [IS_NONCONCURRENT] BIT  NULL ,
	  [REQUESTS_RECOVERY] BIT  NULL 
	)
END
GO

CREATE INDEX IDX_QRTZ_FT_TRIG_INST_NAME ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,INSTANCE_NAME)
CREATE INDEX IDX_QRTZ_FT_INST_JOB_REQ_RCVRY ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,INSTANCE_NAME,REQUESTS_RECOVERY)
CREATE INDEX IDX_QRTZ_FT_J_G ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,JOB_NAME,JOB_GROUP)
CREATE INDEX IDX_QRTZ_FT_JG ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,JOB_GROUP)
CREATE INDEX IDX_QRTZ_FT_T_G ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
CREATE INDEX IDX_QRTZ_FT_TG ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,TRIGGER_GROUP)
GO